"use strict";function d(...c){return e=>c.reduce((n,r)=>r(n),e)}var h=/<head\b[^>]*>([\s\S]*?)<\/head>/gi,x=/<title\b[^>]*>([\s\S]*?)<\/title>/i;function m(c){return c.replace(h,(e,n)=>{let r=n.match(x),t=r?r[0]:"";return`<head>
        <!--
            currentTime: ${Date.now()}
            currentUrl: ${window.location.href}
        -->
        ${t}
    </head>`})}function f(c){return c.replace(/<(\w+)(\s+[^>]*)?>/gi,(e,n,r)=>{if(!r)return`<${n}>`;let t="",s=r.match(/\s+id\s*=\s*["']([^"']*)["']/i);s&&(t+=` id="${s[1]}"`);let o=r.match(/\s+class\s*=\s*["']([^"']*)["']/i);return o&&(t+=` class="${o[1]}"`),`<${n}${t}>`})}function g(c){let e=c;try{let n=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi;e=e.replace(n,"");let r=/<noscript\b[^<]*(?:(?!<\/noscript>)<[^<]*)*<\/noscript>/gi;e=e.replace(r,"");let t=/<img\b[^>]*\/?>/gi;e=e.replace(t,"");let s=/<svg\b[^<]*(?:(?!<\/svg>)<[^<]*)*<\/svg>/gi;e=e.replace(s,""),e=e.replace(/<svg[^>]*>[\s\S]*?<\/svg>/gi,"");let o=/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi;e=e.replace(o,"");let i=/<link\b[^>]*\/?>/gi;e=e.replace(i,"");let a=/<meta\b[^>]*(?:stylesheet|css)[^>]*\/?>/gi;e=e.replace(a,"");let l=/<!--[\s\S]*?-->/gi;e=e.replace(l,"")}catch(n){}return e}function p(c){let e=0;return c.replace(/<iframe\b([^>]*)>/gi,(n,r)=>{let t={},s=r.match(/\s+id\s*=\s*["']([^"']*)["']/i);s&&(t.id=s[1]);let o=r.match(/\s+class\s*=\s*["']([^"']*)["']/i);o&&(t.class=o[1]);let i=r.match(/\s+src\s*=\s*["']([^"']*)["']/i);i&&(t.src=i[1]);let a=JSON.stringify(t),l=`
<!-- IFRAME_PLACEHOLDER:${e}:${a} -->
`;return e++,l}).replace(/<\/iframe>/gi,"")}function u(c){let e=[],n=document.querySelectorAll("iframe");for(let r=0;r<n.length;r++){let t=n[r],s={index:r,src:t.src||"",id:t.id||"",className:t.className||"",accessible:!1};try{t.contentDocument&&t.contentDocument.body&&(s.accessible=!0,s.content=c(t.contentDocument.body.innerHTML))}catch(o){s.accessible=!1}e.push(s)}return e}(function(){function c(t){let s=t;try{s=d(g,p,m,f)(s)}catch(o){}return s}let e=u(c),n=document.documentElement.outerHTML;return{html:c(n),iframes:e,hasIframes:e.length>0}})();
