#!/bin/bash

# Headhunter Platform - Smart Local Setup Script
# Author: AI Assistant
# Description: Automates environment setup for local development without Docker

set -e # Exit on error

# ANSI Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Starting Headhunter Platform Local Setup...${NC}"

# 1. Node Version Check
echo -e "\n${YELLOW}[1/5] Checking Node.js environment...${NC}"
CURRENT_NODE=$(node -v | cut -d'.' -f1 | sed 's/v//')
REQUIRED_NODE=18

if [ "$CURRENT_NODE" -gt 22 ]; then
    echo -e "${YELLOW}⚠️  Warning: You are running Node v$CURRENT_NODE.${NC}"
    echo -e "   Some dependencies (like fast-jwt) may output warnings."
    echo -e "   Recommended version: v$REQUIRED_NODE (LTS)."
    # We don't exit here, just warn
elif [ "$CURRENT_NODE" -lt "$REQUIRED_NODE" ]; then
    echo -e "${RED}❌ Error: Node.js version must be >= $REQUIRED_NODE. Current: v$CURRENT_NODE${NC}"
    exit 1
else
    echo -e "${GREEN}✓ Node.js version v$CURRENT_NODE is compatible.${NC}"
fi

# 2. Environment Configuration
echo -e "\n${YELLOW}[2/5] Configuring Environment Variables...${NC}"

# Backend .env
if [ ! -f backend/.env ]; then
    echo "   Creating backend/.env from example..."
    # Check if example exists, otherwise create minimal
    if [ -f backend/.env.example ]; then
        cp backend/.env.example backend/.env
    else
        echo "   Creating fresh .env..."
        touch backend/.env
    fi
    
    # Smart replacement for Localhost
    # Remove existing DB/Redis configs to avoid duplicates if we append
    # Here we just overwrite with known good local defaults for this script
    
    echo -e "${YELLOW}   📝 Please configure your local database connection:${NC}"
    read -p "   Database User (default: postgres): " DB_USER
    DB_USER=${DB_USER:-postgres}
    
    read -s -p "   Database Password (default: headhunter_pass): " DB_PASS
    echo ""
    DB_PASS=${DB_PASS:-headhunter_pass}
    
    read -p "   Database Name (default: headhunter_platform): " DB_NAME
    DB_NAME=${DB_NAME:-headhunter_platform}

    # Write config
    cat > backend/.env << EOL
NODE_ENV=development
PORT=4000
# Auto-generated by setup-local.sh
DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}?schema=public"
REDIS_URL="redis://localhost:6379"
JWT_SECRET="headhunter-jwt-secret-key-for-development-local"
JWT_EXPIRES_IN="1h"
JWT_REFRESH_EXPIRES_IN="7d"
# Add OCR keys here if needed
# ALIYUN_OCR_ACCESS_KEY=
# ALIYUN_OCR_SECRET=
EOL
    echo -e "${GREEN}✓ Backend configuration created.${NC}"
else
    echo -e "${GREEN}✓ Backend .env already exists. Skipping overwrites.${NC}"
fi

# Frontend .env
if [ ! -f frontend/.env.local ]; then
    echo "NEXT_PUBLIC_API_URL=http://localhost:4000/api" > frontend/.env.local
    echo -e "${GREEN}✓ Frontend configuration created.${NC}"
fi

# 3. Dependencies
echo -e "\n${YELLOW}[3/5] Installing Dependencies...${NC}"
echo "   Installing Backend..."
(cd backend && npm install)
echo "   Installing Frontend..."
(cd frontend && npm install)

# 4. Database Setup
echo -e "\n${YELLOW}[4/5] Setting up Database...${NC}"
echo "   Syncing database schema (Prisma Push)..."
# Use db push instead of migrate deploy to be more tolerant of dev changes
(cd backend && npx prisma db push)

echo "   Seeding initial data..."
(cd backend && npm run db:seed || echo -e "${YELLOW}⚠️  Seeding failed (maybe data exists already). Continuing...${NC}")

# 5. Summary
echo -e "\n${GREEN}🎉 Setup Complete!${NC}"
echo -e "You can now start the application with:"
echo -e "${YELLOW}   cd headhunter-platform && npm run dev${NC}"


